### ISSUE TITLE
Complex Assignment not working

### ISSUE THREAD

**Issue by ryanitus** [eiiches/jackson-jq#115]
From the [JQ manual on Complex Assignment](https://stedolan.github.io/jq/manual/#Assignment), this function should work:

`(.posts[] | select(.author == "stedolan") | .comments) |= . + ["terrible."]`

However, it still returns an exception for:

`IllegalJsonArgumentException: left hand side must be FieldAccess`

According to [Issue 7](https://github.com/eiiches/jackson-jq/issues/7), this was recently fixed in preview and closed, but I'm able to reproduce on `jackson-jq-1.0.0-preview.20210610.jar`.

Here's an [example on jqPlay](https://jqplay.org/s/SBWOgI7NnW)

**Comment by eiiches** [comment]
Hmm, I can't reproduce the issue. Can you post the full console log or something so that I can run the exact same command?

```console
$ java -jar jackson-jq-cli-1.0.0-preview.20210610.jar '(.posts[] | select(.author == "stedolan") | .comments) |= . + ["terrible."]'
{"posts":
    [
        {
            "author":"ryan",
            "comments": ["hello"]
        },
        {
            "author":"stedolan",
            "comments": ["hello"]
        }
    ]
}
{
  "posts" : [ {
    "author" : "ryan",
    "comments" : [ "hello" ]
  }, {
    "author" : "stedolan",
    "comments" : [ "hello", "terrible." ]
  } ]
}
```

**Comment by ryanitus** [comment]
Appreciate the prompt response.  I was indeed using a previous version.  I can confirm it is working now.  Thanks!
