### ISSUE TITLE
Updating non-existing arrays throws exception

### ISSUE THREAD

**Issue by grav** [eiiches/jackson-jq#19]
I discovered a difference between `jq` and `jq-jackson`, shown via this simple example:

```
$ echo '{"foo":[2]}' | jq -c '.foo[]? |= . + 2'
{"foo":[4]}

$ echo '{"foo":null}' | jq -c '.foo[]? |= . + 2'
{"foo":null}

```

The first example works with jackson-jq, the second throws:

```
JsonQueryException Cannot iterate over null  net.thisptr.jackson.jq.internal.misc.JsonNodeUtils.mutate (JsonNodeUtils.java:237)
```

**Comment by eiiches** [comment]
Thanks for reporting the issue and sorry for the lack of communication here. This issue has been resolved in `develop/1.x` branch and `1.0.0-preview.*` versions.
