### ISSUE TITLE
Improved quarkus support: make the jq json node model public 

### ISSUE THREAD

**Issue by lburgazzoli** [eiiches/jackson-jq#195]
As follow up for https://github.com/eiiches/jackson-jq/issues/137, in order to improve the quarkus integration, it would be nice to make  a [JqJson](https://github.com/eiiches/jackson-jq/blob/dcb4836162edcb6a3ef9f18d3da396f0b23937d5/jackson-jq/src/main/java/net/thisptr/jackson/jq/BuiltinFunctionLoader.java#L39-L59) data structure open so it can be used outside the project.

The main reasoning about this is that with quarkus, we can load and process the jq.json files during the build phase so we need a way to unmarshal the content of the  jq.json (similar to what it is done [here](https://github.com/eiiches/jackson-jq/blob/dcb4836162edcb6a3ef9f18d3da396f0b23937d5/jackson-jq/src/main/java/net/thisptr/jackson/jq/BuiltinFunctionLoader.java#L96-L117)).

If this is something that can be acceptable, I can send a PR

**Comment by eiiches** [comment]
Sure, I don't mind making JsJson public as long as it's moved to the `internal` package and it's marked with `@InterfaceAudience("https://github.com/quarkiverse/quarkus-jackson-jq")` or something to restrict/clarify who uses the class.

Please expect some change in the future though. We are probably going to deprecate jq.json and JqJson eventually now that we have a module feature that can load functions from a .jq file. I'll let you know when/if the change to the quarkus-jackson-jq is necessary :+1:

**Comment by eiiches** [comment]
Thanks for the PRs! I plan to release a new version in a few days with your changes.

**Comment by eiiches** [comment]
Just released `1.0.0-preview.20220705`. The jar will be available shortly (there's a delay) from the Maven Central.
