### ISSUE TITLE
Add support for jq `walk`

### ISSUE THREAD

**Issue by btiernay** [eiiches/jackson-jq#2]
Please see:

https://stedolan.github.io/jq/manual/#walk(f)

From [builtin.jq](https://raw.githubusercontent.com/stedolan/jq/master/src/builtin.jq):

```jq
# Apply f to composite entities recursively, and to atoms
def walk(f):
  . as $in
  | if type == "object" then
      reduce keys[] as $key
        ( {}; . + { ($key):  ($in[$key] | walk(f)) } ) | f
  elif type == "array" then map( walk(f) ) | f
  else f
  end;
```

**Comment by btiernay** [comment]
Also, VERY cool project here. I was hoping someone would create this exact project with Jackson integration. Great work!

**Comment by eiiches** [comment]
@btiernay I'm glad to hear that and thanks for the pull request!
