### ISSUE TITLE
Certain keys not allowed

### ISSUE THREAD

**Issue by grav** [eiiches/jackson-jq#20]
I know this is kind of a weird edge-case, but thought I'd document it anyway:

```
$ echo '{"foreach":42}' | jq -c '.foreach'
42
```

Throws exception in jackson-jq:
```
ParseException Encountered " "foreach" "foreach "" at line 1, column 2.
Was expecting one of:
    <EOF> 
    "
...
```

**Comment by eiiches** [comment]
Thank you for reporting!

Hmm... As keywords are already allowed as keys in object construction (e.g. `{foreach: 42}`), this shouldn't be hard to fix. Let me look into this again tomorrow.

In the meantime, as you may know, you can always use `."foreach"` or `.["foreach"]` instead :)
