### ISSUE TITLE
how to use jackson-jq to impliment replace  and append?

### ISSUE THREAD

**Issue by donsonZhang** [eiiches/jackson-jq#23]
jq -s '.[0] * {"channel_group":{"groups":{"Application":{"groups": {"Org3MSP":.[1]}}}}}' config.json org3.json  > modified_config.json

config.json: {"channel_group":{"groups":{"Application":{"groups": {"Org1MSP":"org1"}}}}}
org3.json:{\"sex\":\"man\"}"

how to use jackson-jq to impliment  it?

**Comment by lutzhorn** [comment]
What is the input? What is the expected output?

**Comment by eiiches** [comment]
I'm closing this for now. Please reopen if you need any help.
