### ISSUE TITLE
Object constructor with implicit name from variable throws ParseException

### ISSUE THREAD

**Issue by Atonement100** [eiiches/jackson-jq#24]
Fails:
`jsonQuery = JsonQuery.compile(".userId as $uid | {$uid}");`

Succeeds:
`jsonQuery = JsonQuery.compile(".userId as $uid | {\"userId\": $uid}");`
`jsonQuery = JsonQuery.compile(".userId as $uid | {userId}");`

I believe the first should perform the same as either of the others which succeed (except with a different name, "uid" in its case) per https://jqplay.org/s/pfvuR4JLfc

Is this something I've missed from the list of missing features or a bug? Obviously, the first successful query I've mentioned is an acceptable workaround, just a tad unnecessarily verbose.

**Comment by Atonement100** [comment]
`     [java] Caused by: net.thisptr.jackson.jq.internal.javacc.ParseException: Encountered " "$" "$ "" at line 1, column 20.
     [java] Was expecting one of:
     [java]     "and" ...
     [java]     "or" ...
     [java]     "(" ...
     [java]     "@" ...
     [java]     "}" ...
     [java]     "true" ...
     [java]     "false" ...
     [java]     "null" ...
     [java]     "\"" ...
     [java]     "if" ...
     [java]     "then" ...
     [java]     "elif" ...
     [java]     "else" ...
     [java]     "end" ...
     [java]     "as" ...
     [java]     "def" ...
     [java]     "reduce" ...
     [java]     "foreach" ...
     [java]     "try" ...
     [java]     "catch" ...
     [java]     "label" ...
     [java]     "import" ...
     [java]     "include" ...
     [java]     "module" ...
     [java]     <IDENTIFIER> ...
     [java]
     [java] 	at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.generateParseException(JsonQueryParser.java:2258)
     [java] 	at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.jj_consume_token(JsonQueryParser.java:2123)
     [java] 	at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.ObjectConstruction(JsonQueryParser.java:751)
     [java] 	at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.PrimaryExpression(JsonQueryParser.java:488)
     [java] 	at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.BinaryOperatorExpression(JsonQueryParser.java:226)
     [java] 	at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.TupleExpression(JsonQueryParser.java:199)
     [java] 	at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.JsonQuery(JsonQueryParser.java:151)
     [java] 	at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.Start(JsonQueryParser.java:117)
     [java] 	at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.compile(JsonQueryParser.java:22)
     [java] 	at net.thisptr.jackson.jq.JsonQuery.compile(JsonQuery.java:36)
     [java] 	... 3 more`

**Comment by eiiches** [comment]
Okay, I wasn't aware of the feature.

For now, I'll update README to mention this as a current limitation as it may take some time to implement this feature. If anybody is interested, PRs are welcome as always :)

Thanks for reporting, @Atonement100!

**Comment by Atonement100** [comment]
Gotcha, thanks for the feedback and thanks to you for all of your work!

**Comment by Atonement100** [comment]
Awesome, thank you for your efforts!
