### ISSUE TITLE
How to use --raw-output option from Java?

### ISSUE THREAD

**Issue by rakpawel** [eiiches/jackson-jq#240]
Hello,

I'm using jackson-jq for parsing JSONs and mutating them to CSV using `@csv` operator. It works great. 
Wondering if it's possible to have a `--raw-output` operator available from Java? I can see it's available from jackson-jq-cli level.

Thank you.

**Comment by eiiches** [comment]
Once you obtain the [JsonNode](https://fasterxml.github.io/jackson-databind/javadoc/2.13/com/fasterxml/jackson/databind/JsonNode.html) from JsonQuery#apply() call, you can convert it to a String object like this:

```java
JsonNode out; // assuming you already have a JsonNode output

if (out.isTextual()) // if the output is a json string,
  return out.asText(); // get the contained string as is.
return out.toString(); // otherwise, format the output as json; alternately, you can call ObjectMapper#writeValueAsString(out)
```

Actually, jackson-jq-cli is also implemented in (almost) the same way: https://github.com/eiiches/jackson-jq/blob/a8b2a1134e7b339f12a739a8c733c061188bccc9/jackson-jq-cli/src/main/java/net/thisptr/jackson/jq/cli/Main.java#L129-L137

**Comment by eiiches** [comment]
If you have further questions, feel free to reopen.

**Comment by rakpawel** [comment]
Thank you, it's exactly what I was looking for. :+1:
