### ISSUE TITLE
README.md examples use deprecated code

### ISSUE THREAD

**Issue by RedShift1** [eiiches/jackson-jq#27]
```
final JsonQuery compile = JsonQuery.compile("...");
q.apply(jsonNode); <- deprecated
```

```
Scope scope = new Scope(); <- deprecated
```

**Comment by eiiches** [comment]
Thanks for reminding me. I'll update README.md soon.

In the meantime, please refer to the example in README.md on branch-1. It should work for versions > 0.0.9.
https://github.com/eiiches/jackson-jq/tree/branch-1#usage
