### ISSUE TITLE
Recommended substitute for JsonQuery.apply?

### ISSUE THREAD

**Issue by lutzhorn** [eiiches/jackson-jq#31]
This is deprecated:

https://github.com/eiiches/jackson-jq/blob/cc80601685a631c808008eaa9f431b1698b53684/jackson-jq/src/main/java/net/thisptr/jackson/jq/JsonQuery.java#L20

So far I have used something like this:

```java
JsonQuery query = ...;
ObjectMapper mapper = new ObjectMapper();
JsonNode in = mapper.readTree(someStringContainingAnArray);
List<JsonNode> resultOfQuery = query.apply(in);
```

What is the recommended substitute for `JsonQuery.apply(JsonNode)? What `Scope` should be passed as the first argument to this?

https://github.com/eiiches/jackson-jq/blob/cc80601685a631c808008eaa9f431b1698b53684/jackson-jq/src/main/java/net/thisptr/jackson/jq/JsonQuery.java#L17

**Comment by eiiches** [comment]
@lutzhorn Sorry for the confusion. Please refer to [Usage.java](https://github.com/eiiches/jackson-jq/blob/develop/jackson-jq/src/test/java/examples/Usage.java).

Your code will probably look like this:
```java
// loading functions is costly, so it should be done only once, for example, using static initializers.
private static Scope rootScope;
static {
    rootScope = Scope.newEmptyScope();
    rootScope.loadFunctions(Scope.class.getClassLoader());
}

...

JsonQuery query = ...;
ObjectMapper mapper = new ObjectMapper();
JsonNode in = mapper.readTree(someStringContainingAnArray);
Scope childScope = Scope.newChildScope(rootScope);
List<JsonNode> resultOfQuery = query.apply(childScope, in);
```

If you have further questions, feel free to reopen.
