### ISSUE TITLE
to_entries doesn't work for arrays

### ISSUE THREAD

**Issue by kszafran** [eiiches/jackson-jq#32]
First of all, thanks for this great library, I found it really useful!

I stumbled upon a difference in the implementation of `to_entries`. While jq manual does not seem to mention it, `to_entries` can be used on arrays, like this:
```
$ jq --version
jq-1.6
$ jq -n '["a", "b", "c"] | to_entries'
[
  {
    "key": 0,
    "value": "a"
  },
  {
    "key": 1,
    "value": "b"
  },
  {
    "key": 2,
    "value": "c"
  }
]
```

jackson-jq only accepts objects as input to `to_entries`.

**Comment by kszafran** [comment]
My workaround for this (if I don't need to use it on objects):
```
def to_entries: [keys, .] | transpose | map({key: .[0], value: .[1]});
```

**Comment by eiiches** [comment]
@kszafran Thanks! I checked multiple jq versions, and this behavior seems to have long been there ever since they added `to_entries` in jq-1.3, which I never noticed.
I'll merge your PR shortly.
