### ISSUE TITLE
Support for fromdateiso8601 and todateiso8601

### ISSUE THREAD

**Issue by nikhilunni** [eiiches/jackson-jq#321]
Hi, our organization would like to make use of `fromdateiso8601`, and `todateiso8601`. 
Have a change ready to add to the core list of functions, if they make sense there.

**Comment by eiiches** [comment]
Sure, I'm willing to review and merge them if you send a pull request. I see that they are part of the jq builtins (https://jqlang.github.io/jq/manual/#dates) so there's no reason not to add them to jackson-jq as well.
