### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by eiiches** [eiiches/jackson-jq#328]
### Tasks

- [ ] Disallow the use of "bare" jq functions from the jackson-jq-extra jar.
  - The jq functions that were made available just by putting a jackson-jq-extra jar on the java classpath (`strftime`, `strptime`, `uuid4`, etc.) will be removed. Users must migrate to a new `jackson-jq/extras` jq module. E.g. `import "jackson-jq/extras" as extras; extras::uuid4`
  - WHY: To avoid the future name collisions with the standard jq functions. This is a breaking change and is only possible with a major version bump.
  - TODO: How do we notify users of this change? What should we do for their smooth and successful migration?
    - Should we rename jackson-jq-extra jar to jackson-jq-extras-jq-module or something, so that users can choose whether to keep using the bare functions (but no updates will be provided) or to use the new module system?
- [ ] ... anything else?

### Schedule

TBD

**Comment by davsclaus** [comment]
Would it be possible to release the current code as-is as a 1.0 release. Its stable and users are able to use what was released but they are censored with the release has -preview in the version number. So having a 1.0 release would be much appreciated.

The Apache Camel project is integrated with jq with our camel-jq component. However we have those concerns about a lack of 1.0 release and active maintenance.
https://issues.apache.org/jira/browse/CAMEL-2123

**Comment by eiiches** [comment]
Sure, considering it's been stable for a long time, I'll be releasing the current code as 1.0.0 this month.

**Comment by davsclaus** [comment]
Thanks for the update, looking forward to the release

**Comment by eiiches** [comment]
1.0.0 has been released :tada:

**Comment by davsclaus** [comment]
Thank you very much
