### ISSUE TITLE
"del" not working properly

### ISSUE THREAD

**Issue by nsoubelet** [eiiches/jackson-jq#339]
Hello, I just wanted to report a problem I am having with `del`, which does not behave as `jq`.

Version: `1.0.0-preview.20240207`
I created a gist with the input > https://gist.github.com/nsoubelet/b0524536aa7d45bbace2a382e741e252

When running `jq 'del(.items[] | select(.spec.template.spec.containers[].image == "rancher/local-path-provisioner:v0.0.24"))'` the array element is removed, as expected.

However, when trying the same operation with `jackson-jq` the element is not removed.

Thanks

**Comment by eiiches** [comment]
I couldn't reproduce it myself. The array element seems to be removed as expected.

```console
$ curl -sfLO https://gist.githubusercontent.com/nsoubelet/b0524536aa7d45bbace2a382e741e252/raw/65268045a589733a1c0eedd782cb2b758bba2a82/deployments.json
$ curl -sfLO https://repo1.maven.org/maven2/net/thisptr/jackson-jq-cli/1.0.0-preview.20240207/jackson-jq-cli-1.0.0-preview.20240207.jar
$ cat deployments.json | java -jar jackson-jq-cli-1.0.0-preview.20240207.jar 'del(.items[] | select(.spec.template.spec.containers[].image == "rancher/local-path-provisioner:v0.0.24"))' | jq -r '.items[]|.metadata.name'
coredns
metrics-server
csi-nfs-controller
```

As you can see, there's no `local-path-provisioner` in the result, which was in the original Deployment list.

```console
$ cat deployments.json | jq -r '.items[]|.metadata.name'
local-path-provisioner
coredns
metrics-server
csi-nfs-controller
```

I also confirmed that the jq produces the same result. Can you check the jackson-jq version and try again?

**Comment by nsoubelet** [comment]
Thanks for confirming @eiiches
It's strange, it's probably the case that I am missing something.

Version:
```
<dependency>
    <groupId>net.thisptr</groupId>
    <artifactId>jackson-jq</artifactId>
    <version>1.0.0-preview.20240207</version>
</dependency>
```
Snippet:
```
final Scope scope = Scope.newEmptyScope();
BuiltinFunctionLoader.getInstance().loadFunctions(Version.LATEST, scope);

final JsonQuery q = JsonQuery.compile(
                "del(.items[] | select(.spec.template.spec.containers[].image == \"rancher/local-path-provisioner:v0.0.24\"))",
                Versions.JQ_1_6);

JsonNode in = Serializer.jsonMapper().readTree(
                IOUtils.toString(this.getClass().getClassLoader()
                        .getResourceAsStream("kubernetes/deployment-list-kube-system.json")));

q.apply(
    scope,
    in,
    (outNode) -> {
        try {
            log.info(Serializer.asJsonPrettified(outNode));
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
    });
```
`Serializer` is only a helper class that wraps some standard Mapper's functionality.

**Comment by nsoubelet** [comment]
Hi @eiiches 
Thanks for confirming. It was my mistake, just added in my code what the CLI is doing and it's now working as expected.
