### ISSUE TITLE
Jackson JQ automatically sorts resulting node

### ISSUE THREAD

**Issue by mgsantositrs** [eiiches/jackson-jq#36]
When I used the following query : ". | {name | .name , age | .age} the resulting nodes keys are sorted so it will return {age : "", name : ""}.

**Comment by eiiches** [comment]
Do you want to preserve the key order?

I tend to think JSON object as an unordered collection of key-values, so I never tried to preserve or sort the keys. It will be probably not easy to fix all places that break the order. For now, I'd consider this as a limitation of jackson-jq.

Still, the result being sorted (and not in some random order) is not what I expect. I think I need to look closer tomorrow.

**Comment by eiiches** [comment]
I tried to reproduce and it turned out that keys are not sorted (alphabetically). jackson-jq just does not try to preserve their order, so the results differ depending on JDK version, etc.
```sh
# on my machine
$ jackson-jq -n '{name: "foo", age: 20}'
{
  "name" : "foo",
  "age" : 20
}
```
For now, please use arrays if the order is important.

**Comment by eiiches** [comment]
I'm closing this issue. Feel free to reopen if this is still an issue for you.

**Comment by eiiches** [comment]
related: #81
