### ISSUE TITLE
Make jackson-jq JDK11 compatible

### ISSUE THREAD

**Issue by AlexeyRedinskii** [eiiches/jackson-jq#37]
Hello guys, we are in the process of migrating to JDK11 and your library is not compatible with JDK11 because of transient dependency: org.jruby.joni:joni:2.1.11.

I talked the them to release a compatible version which they recently did https://github.com/jruby/joni/issues/42. Could you please release a new JDK11 compatible version?
Thank you.

**Comment by AlexeyRedinskii** [comment]
@eiiches for you I guess.

**Comment by AlexeyRedinskii** [comment]
Is this project still alive?

**Comment by eiiches** [comment]
Sorry for the delay. I'll release an updated version in 1-2 days.

**Comment by eiiches** [comment]
Just released `0.0.10` jars with an updated joni dependency to the central. It may take up to a few hours to propagate.
