### ISSUE TITLE
regarding 1.2.0 release availablity

### ISSUE THREAD

**Issue by Fkawala** [eiiches/jackson-jq#402]
Hello,

Thank you for the great work made with version 1.2.0 🎉 

Would it be possible to release the binaries 📦  for this version ?

Have a great day,

**Comment by eiiches** [comment]
Hi, @Fkawala 

Hmm... it *is* available on the Maven Central: https://repo1.maven.org/maven2/net/thisptr/jackson-jq/1.2.0/
Maybe the sync had been unusually delayed, can you try downloading it again?
