### ISSUE TITLE
Assignment to object property in an array of objects fails

### ISSUE THREAD

**Issue by mslinn** [eiiches/jackson-jq#41]
I want to write a value to an inner object. Here is the jq/bash code, which works:

```
X="$( jq '(.profiles[] | select(.name=="Ubuntu") | .cursorShape)="vintage"' "$WTJ" )" && echo "$X" > "$WTJ"
```

[This is the data file](https://gist.github.com/mslinn/745ba8b64bc2a4c464279decf6190bdf).

This is some Scala code that is supposed to mirror the above jq/bash code:

```scala
  import com.fasterxml.jackson.databind.{JsonNode, ObjectMapper}
  val file = new java.io.File("/mnt/c/Users/mslinn/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/RoamingState/profiles.json")
  val json: JsonNode = new ObjectMapper().readTree(file)

  val cursorShape = "vintage"
  val query = s""".profiles[] | select(.name=="Ubuntu") | .cursorShape)="$cursorShape""""
  val newJson: Seq[JsonNode] = jq(json, query)
```
When the program runs, and tries to compile the query, I get the error `java.lang.IllegalStateException: Unexpected ')' at line 1, column 53.`. Is there another way to update an object within an array of objects?

**Comment by eiiches** [comment]
@mslinn Hi!

The direct cause of the exception is that, the line

>  val query = s""".profiles[] | select(.name=="Ubuntu") | .cursorShape)="$cursorShape""""

is missing an opening parenthesis at the start. Unfortunately, as you might have tried already, fixing that will get you another exception...

In fact, this type of assignment had long been an issue, and none of the currently released versions of jackson-jq are not capable of handling them. You need [branch-1](https://github.com/eiiches/jackson-jq/tree/branch-1) for this.

For now, is it possible for you to rewrite your query to something like
```
.profiles |= map(if .name == "Ubuntu" then .cursorShape = "vintage" else . end)
```
as a workaround?

**Comment by mslinn** [comment]
Thanks for catching the missing opening parenthesis, and for the workaround, which works. 

I don't need 1:1 compatibility between jq and this project, I just need something that works and is understandable. Your workaround is fine, thanks. I'll add the information to the lecture I am writing for the [Introduction to Scala](https://www.scalacourses.com/showCourse/40) course that discusses `jackson-jq`.
