### ISSUE TITLE
package net.thisptr.jackson.jq.internal.javacc does not exist

### ISSUE THREAD

**Issue by AllenHan5** [eiiches/jackson-jq#52]
when I was trying to make a build of it, and the error happened.
Thanks

**Comment by AllenHan5** [comment]
never mind. when I switched to branch master/1.x, the issue went away.

**Comment by eiiches** [comment]
Are you using an IDE? Some IDEs can't automatically invoke javacc, so you probably need to run `mvn javacc:javacc` (or `mvn package`, which automatically invokes javacc) yourself. Also, be sure to add target/generated-sources/javacc to your build path.

**Comment by eiiches** [comment]
Feel free to reopen if you have further questions.
