### ISSUE TITLE
Bundle net.thisptr.jackson-jq-extra requires internal packages from net.thisptr.jackson-jq

### ISSUE THREAD

**Issue by andreasherkner** [eiiches/jackson-jq#54]
The extra bundle net.thisptr.jackson-jq-extra imports the packages net.thisptr.jackson.jq.internal.misc and net.thisptr.jackson.jq.internal but they are not exported by the main bundle net.thisptr.jackson-jq. It cannot be used/installed in an OSGi environment.

**Comment by eiiches** [comment]
I don't use OSGi and can't be of any help here. If someone can fix this issue, I'd happy to review and accept a PR to support OSGi environment.

**Comment by andreasherkner** [comment]
It's the default behavior of the maven-bundle-plugin: https://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html#_default_behavior

You can add the packages to the <Export-Package>-instruction: 
`<Export-Package>net.thisptr.jackson.jq.*,net.thisptr.jackson.jq.internal.*</Export-Package>`

**Comment by eiiches** [comment]
Thanks for the suggestion. I see. Let me think a bit if we can move/rename some classes so that jackson-jq-extra (or others) doesn't have to depend on the internal package to auto-load a custom function.

**Comment by eiiches** [comment]
Is there any easy way to make sure this kind of issue never happens again? I was looking for an option that automatically fails a build if unexported package from other bundle is used, but maven-bundle-plugin doesn't seem to have one.

**Comment by andreasherkner** [comment]
I don't think, there is an easy way ;)

**Comment by eiiches** [comment]
Oh, okay... I'll merge #106 which makes jackson-jq-extra no longer depend on the internal package. Hopefully it should fix the issue :)
