### ISSUE TITLE
Release version 0.0.3 to Maven Central

### ISSUE THREAD

**Issue by btiernay** [eiiches/jackson-jq#6]
It would be great if you could please release the latest changes to Maven Central. Thanks so much!

**Comment by licq** [comment]
+1. It is so important that we are using this in production.

**Comment by eiiches** [comment]
@btiernay @licq Sorry for the delay, I've just released v0.0.4 of jackson-jq to the Maven Central. It should be available, normally in a few hours.

**Comment by eiiches** [comment]
v0.0.4 is now available on the Maven Central. Closing the issue.

**Comment by licq** [comment]
Got it. Thank you very much.

**Comment by btiernay** [comment]
Thanks so much!
