### ISSUE TITLE
Request to include now/0 extra function.

### ISSUE THREAD

**Issue by vamsibandarupalli** [eiiches/jackson-jq#75]
Hey, requesting new feature to include now/0 into the library.

Already had a pull request for that by changes. [22(now)](https://github.com/eiiches/jackson-jq/pull/22). Please include it in library.

**Comment by eiiches** [comment]
Hi, #22 needs some changes and unfortunately I believe it is abandoned now. Even though I also would like this feature included in jackson-jq, I don't quite have time right now. You still can add a custom function like this: https://github.com/eiiches/jackson-jq/blob/c2382326ce35653479cf0617bae69eb78f086729/jackson-jq/src/test/java/examples/Usage.java#L38-L45

Sorry for the delayed response.
